baseURL: https://tsojka.com/
languageCode: de-de
title: TSojka Audio
# theme: PaperMod is removed
ignoreLogs:
  - warning-goldmark-raw-html
params:
  author: Thomas Sojka
  description: Willkommen der Seite zu meinem Car-HiFi-Kanal! Tutorials, Reviews
    und Tipps aus der Community, fÃ¼r die Community.

  DateFormat: "January 2, 2006"

  label:
    text: "TSojka Audio"
    icon: "images/tsa.svg"
    iconHeight: 18

  profileMode:
    enabled: true
    title: "ðŸ‘‹ Willkommen der Seite zu meinem Car-HiFi-Kanal auf YouTube!" # optional default will be site title
    subtitle: "Entdecke hochwertige Tutorials, ehrliche Audio-Reviews und smarte Einbautipps aus der Community, fÃ¼r die Community. Dein Hub fÃ¼r DSP-Tuning und Fachwissen."
    imageUrl: "/images/profil.jpg" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Workshops
        url: "/workshops"
      - name: Videos
        url: "/videos"
      - name: Testlabor
        url: "/testlabor"

  socialIcons: # optional
    - name: "youtube"
      url: "https://www.youtube.com/@tsojka"
      
menu:
  main:
    - name: Startseite
      url: /
      weight: 1
    - name: Ãœber mich
      url: /about
      weight: 2
    - name: Videos
      url: /videos
      weight: 3
    - name: Testlabor
      url: /testlabor
      weight: 4
    - name: Workshops
      url: /workshops
      weight: 5
    - name: Kontakt
      url: /kontakt
      weight: 6

markup:
  goldmark:
    renderer:
      unsafe: true